### ISSUE TITLE
CMake Error at CMakeLists.txt:109 (find_package): "FindEigen3.cmake"

### ISSUE THREAD

**Issue by mevol** [PDB-REDO/density-fitness#1]
I am trying to install density fit. I followed the instructions per repo.
As Cmake was not installed I downloaded the binaries for version 3.27.4 from here(https://cmake.org/download/#latest)
unpacked the .dmg followed by 
>>> PATH="/Applications/CMake.app/Contents/bin":"$PATH"
I changed into "build" directory and executed
>>> cmake ..

Here the output:
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:38 (include):
  Policy CMP0145 is not set: The Dart and FindDart modules are removed.  Run
  "cmake --help-policy CMP0145" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /Applications/CMake.app/Contents/share/cmake-3.27/Modules/Dart.cmake:47 (message):
  Policy CMP0145 is not set: The Dart and FindDart modules are removed.  Run
  "cmake --help-policy CMP0145" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:38 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Not using resources since mrc was not found
CMake Error at CMakeLists.txt:109 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

************************************
OS: Ventura, 13.5.1 (22G90)
processor: M1

**Comment by mevol** [comment]
I get the same error for "Findlibmcfp.cmake". Clearly, my cmake verion lacks some packages. Is there a way to get a list of all the packages other than trial and error?

**Comment by mhekkel** [comment]
The warnings about mrc and dart can be ignored. Since you're using macOS, resources are not going to work anyway and the removal of Dart is something specific to the newest cmake version.

But then you need the eigen library. You can find it here: https://eigen.tuxfamily.org/index.php?title=Main_Page

For libmcfp you need to install https://github.com/mhekkel/libmcfp

**Comment by mhekkel** [comment]
But did you read the readme at https://github.com/PDB-REDO/libcifpp ?

Everything should be there.

**Comment by mevol** [comment]
Thank you. Yes I found Eigen and I got to the next level with now asking for "Findzeep.cmake". This is my first time on C, so the whole installation is blank.

**Comment by mevol** [comment]
Thank you. I straight away ended up on density-fit rather than PDB-REDO and then obviously went straight to the what-do-I-need-to-type bit. Apologies for the trouble.
